# Generated by Django 5.0.7 on 2024-07-16 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default=datetime.date(2024, 7, 16), max_length=128),
            preserve_default=False,
        ),
    ]
