# Generated by Django 5.0.7 on 2024-07-16 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employees_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_hired',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
