# Generated by Django 5.0.7 on 2024-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_rename_employees_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='john.doe@example.com', max_length=254, unique=True),
        ),
    ]
