# Generated by Django 5.0.7 on 2024-07-17 10:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_users_email_users_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('identification_number', models.CharField(max_length=30)),
                ('working_from', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.countries')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.departments')),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.identificationtype')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpositions')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
