# Generated by Django 5.0.7 on 2024-07-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employees_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employee_id',
            new_name='user_id',
        ),
    ]
