# Generated by Django 5.0.7 on 2024-07-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_countries_iso3_alter_countries_numcode'),
        ('hr', '0009_rename_user_id_employees_user'),
    ]

    operations = [
    ]
